name: dastore
description: general foundation for flutter development
version: 0.0.3
repository: https://github.com/nomagicisreal/dastore

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.0
  test: ^1.24.0
