name: dastore
description: general constant, value, function for flutter development
version: 0.0.18
repository: https://github.com/nomagicisreal/dastore

environment:
  sdk: ^3.2.3


dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.2.0
  damath: ^0.0.32
  datter: ^0.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter

  lints: ^2.1.0
  test: ^1.24.0
